services:
  api-dev:
    build:
      context: ..
      dockerfile: docker/Backend.Dockerfile
    container_name: zsports-api-dev
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver-dev,1433;Database=ZSportsDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=true"
    depends_on:
      - sqlserver-dev
    networks:
      - zsports-dev-net

  sqlserver-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: zsports-sqlserver-dev
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong_password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - zsports_sql_data:/var/opt/mssql
    networks:
      - zsports-dev-net

  frontend-dev:
    build:
      context: ..
      dockerfile: docker/Frontend.Dockerfile
    container_name: zsports-frontend-dev
    ports:
      - "4200:80"
    environment:
      # Ajusta a c√≥mo el front obtiene la URL de API
      NG_APP_API_BASE_URL: "http://localhost:5001"
    depends_on:
      - api-dev
    networks:
      - zsports-dev-net

networks:
  zsports-dev-net:
    driver: bridge

volumes:
  zsports_sql_data: